# Generated by Django 5.0.7 on 2024-08-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='fileData',
        ),
        migrations.AddField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publications/pdfs/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='fileName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
