# Generated by Django 5.0.7 on 2024-08-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publication_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publications/pdfs/%Y/%m/%d/'),
        ),
    ]
